//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arc4u.Cyphertool.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HelpTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arc4u.Cyphertool.Resources.HelpTexts", typeof(HelpTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------------------------------
        ///|       Arc4u Cyphertool.        |
        ///----------------------------------
        ///
        ///Let you decrypt a text or a file using a certificate or a pfx file.
        ///
        ///With a certificate in the certificate store or keychain.
        ///arc4u.cyphertool decrypt with certificate-store &quot;certifcate friendly name&quot; text &quot;clear text&quot;
        ///
        ///
        ///
        ///                               / pfx &quot;C:\temp\devCert.pfx&quot; -p password \ / text &quot;clear text&quot; \
        ///arc4u.cyphertool decrypt with |                                         |     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DecryptCommand {
            get {
                return ResourceManager.GetString("DecryptCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------------------------------
        ///|       Arc4u Cyphertool.        |
        ///----------------------------------
        ///
        ///Decrypt the content of a file.
        ///
        ///                               / pfx &quot;C:\temp\devCert.pfx&quot; -p password \ 
        ///arc4u.cyphertool encrypt with |                                         | file &quot;path&quot;  -o &quot;file&quot;
        ///                               \ cert &quot;devCert&quot; -l LocalMachine -n My  / 
        ///
        ///
        ///Optionnaly you can specify that the encrypted file content must be saved in a file.
        ///
        ///-o | --output =&gt; The file to  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DecryptFileCommand {
            get {
                return ResourceManager.GetString("DecryptFileCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------------------------------
        ///|       Arc4u Cyphertool.        |
        ///----------------------------------
        ///
        ///Decrypt with a certificate in the certificate store or the keychain searching based on the friendly name to find the certificate in the store.
        ///
        ///
        ///                                                                    / text &quot;clear text&quot; \
        ///arc4u.cyphertool decrypt with cert &quot;devCert&quot; -l LocalMachine -n My |                     | -o &quot;file&quot;
        ///                                                              [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DecryptFromCertificateCommand {
            get {
                return ResourceManager.GetString("DecryptFromCertificateCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------------------------------
        ///|       Arc4u Cyphertool.        |
        ///----------------------------------
        ///
        ///Decrypt from a pfx file.
        ///
        ///
        ///                                                                     / text &quot;clear text&quot; \
        ///arc4u.cyphertool decrypt with pfx &quot;C:\temp\devCert.pfx&quot; -p password |                     | -o &quot;file&quot;
        ///                                                                     \ file &quot;path&quot;       /
        ///
        ///
        ///Optionnaly you can add the password to the pfx file.
        ///-p | --password =&gt; The pass [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DecryptFromPfxCommand {
            get {
                return ResourceManager.GetString("DecryptFromPfxCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------------------------------
        ///|       Arc4u Cyphertool.        |
        ///----------------------------------
        ///
        ///When you use the cypher tool and you want to decrypt a text based on a certificate,
        ///you have to provide the clear text via the text argument like this:
        ///
        ///                               / pfx &quot;C:\temp\devCert.pfx&quot; -p password \ 
        ///arc4u.cyphertool decrypt with |                                         | text &quot;clear text&quot; -o &quot;file&quot;
        ///                               \ cert &quot;devCert&quot; -l LocalMachine -n M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DecryptTextCommand {
            get {
                return ResourceManager.GetString("DecryptTextCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------------------------------
        ///|       Arc4u Cyphertool.        |
        ///----------------------------------
        ///
        ///Let you encrypt a text or a file using a certificate or a pfx file.
        ///
        ///With a certificate in the certificate store or keychain.
        ///arc4u.cyphertool encrypt with certificate-store &quot;certifcate friendly name&quot; text &quot;clear text&quot;
        ///
        ///
        ///
        ///                               / pfx &quot;C:\temp\devCert.pfx&quot; -p password \ / text &quot;clear text&quot; \
        ///arc4u.cyphertool encrypt with |                                         |     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EncryptCommand {
            get {
                return ResourceManager.GetString("EncryptCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------------------------------
        ///|       Arc4u Cyphertool.        |
        ///----------------------------------
        ///
        ///Encrypt the content of a file.
        ///
        ///                               / pfx &quot;C:\temp\devCert.pfx&quot; -p password \ 
        ///arc4u.cyphertool encrypt with |                                         | file &quot;path&quot;  -o &quot;file&quot;
        ///                               \ cert &quot;devCert&quot; -l LocalMachine -n My  / 
        ///
        ///
        ///Optionnaly you can specify that the encrypted file content must be saved in a file.
        ///
        ///-o | --output =&gt; The file to  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EncryptFileCommand {
            get {
                return ResourceManager.GetString("EncryptFileCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------------------------------
        ///|       Arc4u Cyphertool.        |
        ///----------------------------------
        ///
        ///Encrypt with a certificate in the certificate store or the keychain searching based on the friendly name to find the certificate in the store.
        ///
        ///
        ///                                                                    / text &quot;clear text&quot; \
        ///arc4u.cyphertool encrypt with cert &quot;devCert&quot; -l LocalMachine -n My |                     | -o &quot;file&quot;
        ///                                                              [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EncryptFromCertificateCommand {
            get {
                return ResourceManager.GetString("EncryptFromCertificateCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------------------------------
        ///|       Arc4u Cyphertool.        |
        ///----------------------------------
        ///
        ///Encrypt from a pfx file.
        ///
        ///
        ///                                                                     / text &quot;clear text&quot; \
        ///arc4u.cyphertool encrypt with pfx &quot;C:\temp\devCert.pfx&quot; -p password |                     | -o &quot;file&quot;
        ///                                                                     \ file &quot;path&quot;       /
        ///
        ///
        ///Optionnaly you can add the password to the pfx file.
        ///-p | --password =&gt; The pass [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EncryptFromPfxCommand {
            get {
                return ResourceManager.GetString("EncryptFromPfxCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------------------------------
        ///|       Arc4u Cyphertool.        |
        ///----------------------------------
        ///
        ///When you use the cypher tool and you want to encrypt a text based on a certificate,
        ///you have to provide the clear text via the text argument like this:
        ///
        ///                               / pfx &quot;C:\temp\devCert.pfx&quot; -p password \ 
        ///arc4u.cyphertool encrypt with |                                         | text &quot;clear text&quot; -o &quot;file&quot;
        ///                               \ cert &quot;devCert&quot; -l LocalMachine -n M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EncryptTextCommand {
            get {
                return ResourceManager.GetString("EncryptTextCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------------------------------
        ///|       Arc4u Cyphertool.        |
        ///----------------------------------
        ///
        ///Let you extract the public, private and optionally the certificate public key authorities from a pfx certificate.
        ///Let you choose to encrypt the private key with another certificate.
        ///The result will be written in a console or in 2 or 3 files.
        ///
        ///
        ///                                                                                    |                / pfx &quot;C:\temp\devCert.pfx&quot; -p password 
        ///arc4u.cyph [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtractCommand {
            get {
                return ResourceManager.GetString("ExtractCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------------------------------
        ///|       Arc4u Cyphertool.        |
        ///----------------------------------
        ///
        ///Let you extract the public, private and optionally the certificate public key authorities from a pfx certificate.
        ///Let you choose to encrypt the private key with another certificate.
        ///The result will be written in a console or in 2 or 3 files.
        ///
        ///
        ///                                                                                                     
        ///arc4u.cyphertool extract with pfx &quot;C:\temp\devCert [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtractEncryptCertificateStoreCommand {
            get {
                return ResourceManager.GetString("ExtractEncryptCertificateStoreCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------------------------------
        ///|       Arc4u Cyphertool.        |
        ///----------------------------------
        ///
        ///Let you extract the public, private and optionally the certificate public key authorities from a pfx certificate.
        ///Let you choose to encrypt the private key with another certificate.
        ///The result will be written in a console or in 2 or 3 files.
        ///
        ///
        ///                                                                                                     
        ///arc4u.cyphertool extract with pfx &quot;C:\temp\devCert [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtractEncryptPfxCommand {
            get {
                return ResourceManager.GetString("ExtractEncryptPfxCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------------------------------
        ///|       Arc4u Cyphertool.        |
        ///----------------------------------
        ///
        ///Let you extract the public, private and optionally the certificate public key authorities from a pfx certificate.
        ///Let you choose to encrypt the private key with another certificate.
        ///The result will be written in a console or in 2 or 3 files.
        ///
        ///
        ///                                                                                    |                / pfx &quot;C:\temp\devCert.pfx&quot; -p password 
        ///arc4u.cyph [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtractWithPfxCommand {
            get {
                return ResourceManager.GetString("ExtractWithPfxCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      __        _______         ______     _    _     _____  _____ 
        ///     /  \      |_   __ \      .&apos; ___  |   | |  | |   |_   _||_   _|
        ///    / /\ \       | |__) |    / .&apos;   \_|   | |__| |_    | |    | |  
        ///   / ____ \      |  __ /     | |          |____   _|   | &apos;    &apos; |  
        /// _/ /    \ \_   _| |  \ \_   \ `.___.&apos;\       _| |_     \ `--&apos; /   
        ///|____|  |____| |____| |___|   `._____.&apos;      |_____|     `.__.&apos;    
        ///                                                                   
        ///
        ///######## ##    ##  ###### [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RootCommand {
            get {
                return ResourceManager.GetString("RootCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc4u Cyphertool {0}. .
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
