name: Build and publish preview

on: 
  workflow_dispatch:
    inputs:
      nugetVersion:
        description: 'nuget version number x.y.z'     
        required: false
        type: string
        default: '1.0.0'
      nugetPreviewName:
        description: 'nuget preview ?'     
        required: true
        default: '-preview01'
      publish:
        description: 'true or false' 
        type: boolean
        required: true
        default: false
        
jobs:
  build:
    uses: ./.github/workflows/CoreBuild.yml
    with:
      nugetVersion: ${{ github.event.inputs.nugetVersion }}
      nugetPreviewName: ${{ github.event.inputs.nugetPreviewName }}
      publish: ${{ github.event.inputs.publish }}
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}