name: Build And Publish

on: 
  workflow_call:
    inputs:
      nugetVersion:
        description: 'nuget version number x.y.z.w'     
        required: false
        type: string
      nugetPreviewName:
        description: 'nuget preview ?'     
        required: false
        type: string
      publish:
        description: 'Publish to nuget.org?' 
        type: string
        required: true
    secrets:
       NUGET_API_KEY:
         required: true
        
env:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'  
  netVersion: '${{ github.event.inputs.nugetVersion }}'
  netVersionNuget: '${{ github.event.inputs.nugetVersion }}${{ github.event.inputs.nugetPreviewName }}'
  PublishToNuget: ${{ github.event.inputs.publish }}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
           dotnet-version: |
             8.0.303

      - name: setup nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: latest
 
      - name: nuget restore
        run: dotnet restore .\src\Arc4u.Encryptor.sln
 
      - name: build
        run: dotnet build .\src\Arc4u.Encryptor.sln --configuration ${{env.buildConfiguration}} /p:Version=${{env.netVersion}}  
 
      - name: build nuget package with a specific version.
        run: dotnet pack .\src\Arc4u.Encryptor.sln -p:Version=${{env.netVersionNuget}}

      - name: Save nuget packages
        if: ${{ env.PublishToNuget == 'false'  }}
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            .\src\nupkg
          retention-days: 1
        
      - name: Publish packages
        if: ${{ env.PublishToNuget == 'true'  }}
        run: dotnet nuget push ".src\nupkg\*.nupkg" --skip-duplicate --no-symbols --api-key ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
